pipeline:
  name: run-generic-mitigation-demo
  identifier: rungenericmitigationdemo
  projectIdentifier: reliability_engineering
  orgIdentifier: cloudnativeplatform
  tags: {}
  stages:
    - stage:
        name: mitigation
        identifier: mitigation
        template:
          templateRef: rungenericmitigation
          versionLabel: "1.0.3"
          templateInputs:
            type: Custom
            variables:
              - name: target_host
                type: String
                value: <+input>
              - name: target_port
                type: String
                value: <+input>
